export const EMAIL = 'malijahluis@gmail.com'
export const GITHUB = 'https://github.com/alijah-d'
export const LINKEDIN = 'https://www.linkedin.com/in/alijahluis/'
export const TWITTER = 'https://twitter.com/alijahluis'
export const MEDIUM = 'https://medium.com/@malijahluis'